// Generated by Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
#endif

#import <ThemeKit/ThemeKit.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSCoder;

SWIFT_CLASS("_TtC8ThemeKit8TKButton")
@interface TKButton : UIButton
@property (nonatomic) BOOL createdFromNib;
- (void)awakeFromNib;
- (void)didMoveToSuperview;
- (void)setNeedsUpdateTheme;
- (void)layoutSubviews;
@property (nonatomic, copy) NSString * __nullable textStyleId;
@property (nonatomic, copy) NSString * __nullable tintColourId;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ThemeKit7TKLabel")
@interface TKLabel : UILabel
@property (nonatomic) BOOL createdFromNib;
- (void)awakeFromNib;
- (void)didMoveToSuperview;
- (void)setNeedsUpdateTheme;
- (void)layoutSubviews;
@property (nonatomic, copy) NSString * __nullable textStyleId;
@property (nonatomic, copy) NSString * __nullable textColourStyleId;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ThemeKit18TKSegmentedControl")
@interface TKSegmentedControl : UISegmentedControl
@property (nonatomic) BOOL createdFromNib;
- (void)awakeFromNib;
- (void)didMoveToSuperview;
- (void)setNeedsUpdateTheme;
- (void)layoutSubviews;
@property (nonatomic, copy) NSString * __nullable textStyleId;
@property (nonatomic, copy) NSString * __nullable tintColourId;
- (CGSize)intrinsicContentSize;
- (nonnull instancetype)initWithItems:(NSArray * __nullable)items OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ThemeKit9TKStepper")
@interface TKStepper : UIStepper
@property (nonatomic) BOOL createdFromNib;
- (void)awakeFromNib;
- (void)didMoveToSuperview;
- (void)setNeedsUpdateTheme;
- (void)layoutSubviews;
@property (nonatomic, copy) NSString * __nullable tintColourId;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ThemeKit8TKSwitch")
@interface TKSwitch : UISwitch
@property (nonatomic) BOOL createdFromNib;
- (void)awakeFromNib;
- (void)didMoveToSuperview;
- (void)setNeedsUpdateTheme;
- (void)layoutSubviews;
@property (nonatomic, copy) NSString * __nullable onTintColourId;
@property (nonatomic, copy) NSString * __nullable thumbTintColourId;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ThemeKit11TKTextField")
@interface TKTextField : UITextField
@property (nonatomic) BOOL createdFromNib;
- (void)awakeFromNib;
- (void)didMoveToSuperview;
- (void)setNeedsUpdateTheme;
- (void)layoutSubviews;

/// can set to nil to return to set textInsets to the default value but will always return a value
@property (nonatomic, copy) NSString * __nullable textInsetsString;
- (CGSize)intrinsicContentSize;
- (CGRect)textRectForBounds:(CGRect)bounds;
- (CGRect)editingRectForBounds:(CGRect)bounds;
- (CGRect)placeholderRectForBounds:(CGRect)bounds;
@property (nonatomic) UIEdgeInsets textInsets;
@property (nonatomic, copy) NSString * __nullable textStyleId;
@property (nonatomic, copy) NSString * __nullable textColourStyleId;
@property (nonatomic, copy) NSString * __nullable placeholderTextStyleId;
@property (nonatomic, copy) NSString * __nullable placeholderTextColourStyleId;
@property (nonatomic, copy) NSString * __nullable placeholder;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSTextContainer;

SWIFT_CLASS("_TtC8ThemeKit10TKTextView")
@interface TKTextView : UITextView
@property (nonatomic) BOOL createdFromNib;
- (void)awakeFromNib;
- (void)didMoveToSuperview;
- (void)setNeedsUpdateTheme;
- (void)layoutSubviews;
@property (nonatomic, copy) NSString * __nullable textStyleId;
@property (nonatomic, copy) NSString * __nullable textColourStyleId;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * __nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ThemeKit13TKThemeVendor")
@interface TKThemeVendor : NSSingleton
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ThemeKit6TKView")
@interface TKView : UIView
@property (nonatomic) BOOL createdFromNib;
- (void)awakeFromNib;
- (void)didMoveToSuperview;
- (void)setNeedsUpdateTheme;
- (void)layoutSubviews;
@property (nonatomic, copy) NSString * __nullable backgroundColourStyleId;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UILabel (SWIFT_EXTENSION(ThemeKit))
@end


@interface UISearchBar (SWIFT_EXTENSION(ThemeKit))
@end


@interface UITextField (SWIFT_EXTENSION(ThemeKit))
@end


@interface UITextView (SWIFT_EXTENSION(ThemeKit))
@end


@interface UIView (SWIFT_EXTENSION(ThemeKit))
@end


@interface UIView (SWIFT_EXTENSION(ThemeKit))
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
@end

#pragma clang diagnostic pop
